const defaultNodeStyles = {
  input: {
    background: "#4c5b6f",
    color: "#fff",
    border: "4px solid transparent",
    borderRadius: "8px",
    padding: "8px",
    width: "160px",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    backgroundClip: "border-box",
    fontFamily: "inherit",
  },
  default: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "8px",
    width: "auto",
    minWidth: "120px",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  "text-no-bg": {
    background: "transparent",
    color: "#fff",
    border: "none",
    borderRadius: "0px",
    padding: "4px",
    width: "auto",
    minWidth: "120px",
    transition: "none",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "none",
    boxShadow: "none",
    fontFamily: "inherit",
  },
  link: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  "youtube-video": {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "8px",
    width: "320px",
    minWidth: "320px",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  mindmap: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "8px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  spotify: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "8px",
    width: "auto",
    minWidth: "200px",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  soundcloud: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "8px",
    width: "auto",
    minWidth: "200px",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },

  instagram: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  twitter: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  tiktok: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  youtube: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  facebook: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  mindmeet: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "10px",
    width: "auto",
    minWidth: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  image: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "0",
    minWidth: "auto",
    width: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  audio: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "0",
    minWidth: "250px",
    width: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
  playlist: {
    background: "#4c5b6f",
    color: "#fff",
    border: "2px solid #374151",
    borderRadius: "16px",
    padding: "0",
    minWidth: "250px",
    width: "auto",
    transition: "border-color 0.2s ease-in-out",
    wordWrap: "break-word",
    whiteSpace: "pre-wrap",
    overflow: "visible",
    textShadow: "0 1px 2px rgba(0, 0, 0, 1)",
    fontFamily: "inherit",
  },
};

export default defaultNodeStyles;
